apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
  replicas: 3
  selector:
    app: myonlineapp
    version: 2.7.1
  template:
    metadata:
      labels:
        app: myonlineapp
        version: 2.7.1
    spec:
      containers:
        - name: myonlineapp-container
          image: sameerdocker123/myjavaapp22jan22:1
          ports:
          - containerPort: 8080
