apiVersion: v1
kind: Service
metadata:
  name: myonlineapp-rc
  lables:
    app: myonlineapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myonlineapp
    